# Generated by Django 4.1.1 on 2022-09-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('message', models.TextField(max_length=200)),
                ('time_sent', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
